Update patch set 4
Patch Set 4:

This CL has failed the run. Reason:

Tryjob [golang/try/x_crypto-gotip-linux-amd64-misccompile](https://cr-buildbucket.appspot.com/build/8720512222715040737) has failed with summary ([view all results](https://go-review.googlesource.com/c/636257?checksPatchset=4&tab=checks)):

---
* go on master ([commit af92bb5](https://go.googlesource.com/go/+/af92bb594d6daaacdd2d03549911fbec8ae65900))
* crypto on master ([change 636257](https://go-review.googlesource.com/c/crypto/+/636257/4))

Error: `shard 2: failed to run test golang.org/x/crypto module for goos:"linux"  goarch:"loong64": exit status 1`

Additional links for debugging:
* [Output for test golang.org/x/crypto module for goos:"linux"  goarch:"loong64" [shard 2]](https://logs.chromium.org/logs/golang/buildbucket/cr-buildbucket/8720511907786335985/+/u/step/53/log/2)
* [Shard 2 encountered a non-build/non-test failure, click here for the shard's build page](https://ci.chromium.org/b/8720511907786335985)

Patch-set: 4
Tag: autogenerated:cq:dry-run:1741868483
Attention: {"person_ident":"Gerrit User 59718 \u003c59718@62eb7196-b449-3ce5-99f1-c037f21e1705\u003e","operation":"ADD","reason":"ps#4: Tryjobs failed"}
Attention: {"person_ident":"Gerrit User 54019 \u003c54019@62eb7196-b449-3ce5-99f1-c037f21e1705\u003e","operation":"ADD","reason":"ps#4: Tryjobs failed"}