Update patch set 2
Patch Set 2:

> Patch Set 2:
> 
> This needs a test. Can you check where coverage for the other cases comes from, and add testdata for your newly added keytype?
> 
> Is there a RFC or other sort of specification that governs this key type? If yes refer to it.

I am unable to push with a test added in `ssh/testdata/keys.go` and it's getting rejected, how can I proceed:

```
remote: The push has been rejected because we detect that it contains a private
remote: key. Please check the following commands and confirm that it's
remote: intentional:
remote: 
remote:     git show bdaa9cbcb70169378b0b773498e09a65042364ba
remote: 
remote: You can use `git rev-list --objects --all` to find the files.
remote: 
remote: To push these files, please run `git push -o nokeycheck`.
remote: 
To https://go.googlesource.com/crypto
 ! [remote rejected] HEAD -> refs/for/master (found a private key)
error: failed to push some refs to 'https://go.googlesource.com/crypto'
(running: git push -q origin HEAD:refs/for/master)
/home/frezbo/git/work/golang/bin/git-codereview: exit status 1
```

Patch-set: 2
Reviewer: Gerrit User 28654 <28654@62eb7196-b449-3ce5-99f1-c037f21e1705>