Update patch set 2
Patch Set 2:

Thanks for merging, I had to update the patch using my github fork. For some reason [1] I wasn't allowed to push to go.googlesource.com. Now the CLA is set to NO, but I'm giving you a writing consent that I agree on all the terms of the CLA.

[1] 
```
 ! [remote rejected] HEAD -> refs/for/master (cannot add patch set to 215540.)
error: failed to push some refs to 'https://go.googlesource.com/crypto'
```

> Patch Set 1:
> 
> Ah, duh - my fault. You can do this by checking out Filippo's change, and then cherry-picking on top of that. Sorry.
> 
> I submitted Filippo's change, so now you can simply rebase on master.

Patch-set: 2
Reviewer: Gerrit User 34882 <34882@62eb7196-b449-3ce5-99f1-c037f21e1705>