Update patch set 3
Patch Set 3:

> Patch Set 3:
> 
> > Patch Set 3:
> > 
> > > Patch Set 3:
> > > 
> > > > Patch Set 3:
> > > > 
> > > > > --- FAIL: TestAdvance (0.00s)
> > > > > panic: runtime error: index out of range [-1] [recovered]
> > > > > 	panic: runtime error: index out of range [-1]
> > > > > 
> > > > > goroutine 14 [running]:
> > > > > testing.tRunner.func1(0xc0000c0240)
> > > > > 	/home/boger/golang/fresher/go/src/testing/testing.go:916 +0x540
> > > > > panic(0x143580, 0xc0003eb420)
> > > > > 	/home/boger/golang/fresher/go/src/runtime/panic.go:961 +0x14c
> > > > > golang.org/x/crypto/internal/chacha20.(*Cipher).XORKeyStream(0xc0000cc018, 0xc000406d60, 0x0, 0x2, 0xc00001a790, 0x0, 0x50)
> > > > > 	/home/boger/gocode.new/src/golang.org/x/crypto/internal/chacha20/chacha_generic.go:95 +0x370
> > > > > golang.org/x/crypto/internal/chacha20.TestAdvance(0xc0000c0240)
> > > > > 	/home/boger/gocode.new/src/golang.org/x/crypto/internal/chacha20/chacha_test.go:153 +0x130
> > > > > testing.tRunner(0xc0000c0240, 0x16da78)
> > > > > 	/home/boger/golang/fresher/go/src/testing/testing.go:954 +0xd8
> > > > > created by testing.(*T).Run
> > > > > 	/home/boger/golang/fresher/go/src/testing/testing.go:1005 +0x2ec
> > > > 
> > > > Oh right, yeah, thats the panic when len(src) == 0 that I mentioned in my review. That needs fixing.
> > > 
> > > I fixed that one and hit another which I also fixed and then TestAdvance works. But the other failures get wrong answers.
> > 
> > I found the problem in asm_ppc64le.s The function was always updating the counter by 4, instead of by the number of blocks that were processed. I can create a CL to fix this and change the name to chacha_ppc64le.s.
> 
> Thanks for looking into that. Was it a lingering bug or is it introduced by this CL? If the latter, and the patch is small, it might be simpler to apply it in this CL.
> 
> BTW, does any of you two feel comfortable +2'ing this once the issues are fixed? I don't think Adam will have time by tomorrow, and then the Go 1.14 review window closes.

It was a lingering bug. 

Here is the change if you want to just add it. I noticed that the X defines were no longer used so removed them too.

I'd prefer Mike +2 it since he is more familiar with the history of this particular change.

diff --git a/internal/chacha20/asm_ppc64le.s b/internal/chacha20/asm_ppc64le.s
index bc9b562..26a276c 100644
--- a/internal/chacha20/asm_ppc64le.s
+++ b/internal/chacha20/asm_ppc64le.s
@@ -31,24 +31,7 @@
 #define TMP  R15
 
 #define CONSTBASE  R16
-
-#define X0   R11
-#define X1   R12
-#define X2   R14
-#define X3   R15
-#define X4   R16
-#define X5   R17
-#define X6   R18
-#define X7   R19
-#define X8   R20
-#define X9   R21
-#define X10  R22
-#define X11  R23
-#define X12  R24
-#define X13  R25
-#define X14  R26
-#define X15  R27
-
+#define BLOCKS R17
 
 DATA consts<>+0x00(SB)/8, $0x3320646e61707865
 DATA consts<>+0x08(SB)/8, $0x6b20657479622d32
@@ -86,6 +69,7 @@ TEXT ·chaCha20_ctr32_vsx(SB),NOSPLIT,$64-40
        MOVD $32, R9
        MOVD $48, R10
        MOVD $64, R11
+       SRD $6,LEN,BLOCKS
        // V16
        LXVW4X (CONSTBASE)(R0), VS48
        ADD $80,CONSTBASE
@@ -431,7 +415,7 @@ loop_vsx:
 done_vsx:
        // Increment counter by number of 64 byte blocks
        MOVD (CNT), R14
-       ADD  $4, R14
+       ADD  BLOCKS, R14
        MOVD R14, (CNT)
        RET

Patch-set: 3
Reviewer: Gerrit User 6320 <6320@62eb7196-b449-3ce5-99f1-c037f21e1705>