Update patch set 1
Patch Set 1:

Thanks for taking the time, but it looks I lack of "forge author" permissions [1]. According to the docs [2] I should ask for "Forge Committer" access rights or ask you to submit the changes on my behalf, i posted a gist with the necessary changes including the padding change in https://gist.github.com/maraino/5329cc8fd3c67c0e7782b8a68f02e424 if that's easier, I would like to be able though.

On a different subject I have other changes that I would like to submit in the future, probably once Filippo's and this change get to master, as they will require changes, the changes are the support for marshaling keys with the openssh format, with support for both plain and encrypted formats.

Thanks again.

[1]
```
mariano@endor crypto (openssh-ec-keys)$ git push -o nokeycheck "https://go.googlesource.com/crypto" HEAD:refs/for/master
Enumerating objects: 21, done.
Counting objects: 100% (21/21), done.
Delta compression using up to 4 threads
Compressing objects: 100% (15/15), done.
Writing objects: 100% (16/16), 6.79 KiB | 2.26 MiB/s, done.
Total 16 (delta 8), reused 0 (delta 0)
remote: Resolving deltas: 100% (8/8)
remote: Processing changes: refs: 1, done
remote: ERROR: commit 545b558: email address hi@filippo.io is not registered in your account, and you lack 'forge author' permission.
remote: The following addresses are currently registered:
remote:    mariano.cano@gmail.com
remote:    mariano@smallstep.com
remote: To register an email address, visit:
remote: https://go-review.googlesource.com/settings#EmailAddresses
remote:
remote:
To https://go.googlesource.com/crypto
 ! [remote rejected] HEAD -> refs/for/master (commit 545b558: invalid author)
error: failed to push some refs to 'https://go.googlesource.com/crypto'
```

[2] https://gerrit-review.googlesource.com/Documentation/error-invalid-committer.html#_missing_privileges_to_push_commits_that_were_committed_by_other_users) 


> Patch Set 1:
> 
> > Patch Set 1:
> > 
> > I've tried to rebase Filippo's changes in this branch, but Gerrit/git-codereview doesn't allow me to send the changes because I have 'pending' changes (Filippo's commits). I've also created a branch from CL#207600, and applied my changes to it, but got a similar problem. 
> > 
> > To do this, I'm not using my github clone, I've clone crypto from googlesource.com, and used git-codereview to get mine and Filippo's changes (git codereview change <cl-number>).
> > 
> > If you can show me how can I actually be able to commit on top of CL#207600, I'm happy to do it.
> > 
> > > Patch Set 1:
> > > 
> > > Sure I can, I'll need some extra time to configure and figure out how googlesource.com works. It will be easier for me if that change was already on master, and synced to the github repo.
> > > 
> > > > Patch Set 1:
> > > > 
> > > > (1 comment)
> 
> start from a clean branch, ie.
> 
> git checkout -b mychanges origin/master
> 
> # cherry pick filippo's change
> git fetch "https://go.googlesource.com/crypto" refs/changes/00/207600/5 && git cherry-pick FETCH_HEAD
> 
> # cherry-pick your own.
> git cherry-pick 0a37f9d
> 
> # hack hack hack
> 
> # leave the Change-Id line intact.
> git commit --amend
> 
> git push "https://go.googlesource.com/crypto" HEAD:refs/for/master

Patch-set: 1