Update patch set 3
Patch Set 3:

> Patch Set 3:
> 
> > Patch Set 3:
> > 
> > > --- FAIL: TestAdvance (0.00s)
> > > panic: runtime error: index out of range [-1] [recovered]
> > > 	panic: runtime error: index out of range [-1]
> > > 
> > > goroutine 14 [running]:
> > > testing.tRunner.func1(0xc0000c0240)
> > > 	/home/boger/golang/fresher/go/src/testing/testing.go:916 +0x540
> > > panic(0x143580, 0xc0003eb420)
> > > 	/home/boger/golang/fresher/go/src/runtime/panic.go:961 +0x14c
> > > golang.org/x/crypto/internal/chacha20.(*Cipher).XORKeyStream(0xc0000cc018, 0xc000406d60, 0x0, 0x2, 0xc00001a790, 0x0, 0x50)
> > > 	/home/boger/gocode.new/src/golang.org/x/crypto/internal/chacha20/chacha_generic.go:95 +0x370
> > > golang.org/x/crypto/internal/chacha20.TestAdvance(0xc0000c0240)
> > > 	/home/boger/gocode.new/src/golang.org/x/crypto/internal/chacha20/chacha_test.go:153 +0x130
> > > testing.tRunner(0xc0000c0240, 0x16da78)
> > > 	/home/boger/golang/fresher/go/src/testing/testing.go:954 +0xd8
> > > created by testing.(*T).Run
> > > 	/home/boger/golang/fresher/go/src/testing/testing.go:1005 +0x2ec
> > 
> > Oh right, yeah, thats the panic when len(src) == 0 that I mentioned in my review. That needs fixing.
> 
> I fixed that one and hit another which I also fixed and then TestAdvance works. But the other failures get wrong answers.

I found the problem in asm_ppc64le.s The function was always updating the counter by 4, instead of by the number of blocks that were processed. I can create a CL to fix this and change the name to chacha_ppc64le.s.

Patch-set: 3
Reviewer: Gerrit User 6320 <6320@62eb7196-b449-3ce5-99f1-c037f21e1705>